# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_auto_20170404_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controller',
            old_name='controller',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='template',
            old_name='template',
            new_name='file',
        ),
    ]
