# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0014_auto_20170420_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='controller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Controller'),
        ),
        migrations.AlterField(
            model_name='post',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Template'),
        ),
    ]
