# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0015_auto_20170420_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='priority',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
