# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0016_page_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='priority',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
