# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0019_auto_20170428_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='template',
            name='parameters',
            field=models.TextField(blank=True, null=True),
        ),
    ]
