# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0022_auto_20170511_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='video',
            new_name='videos',
        ),
    ]
