# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0024_video_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='priority',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
