# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0028_auto_20170530_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
