# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='header',
            name='pages',
            field=models.ManyToManyField(to='core.Page'),
        ),
        migrations.AddField(
            model_name='config',
            name='footer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Footer'),
        ),
        migrations.AddField(
            model_name='config',
            name='header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Header'),
        ),
    ]
