# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170419_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_date',
            new_name='created_datetime',
        ),
    ]
