# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170419_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sidebar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Controller')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Template')),
            ],
        ),
        migrations.AddField(
            model_name='config',
            name='left_sidebar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_sidebar', to='core.Sidebar'),
        ),
        migrations.AddField(
            model_name='config',
            name='right_sidebar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_sidebar', to='core.Sidebar'),
        ),
    ]
