# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_widget_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Controller')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Template')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='core.Category'),
        ),
    ]
