# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20170504_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='file',
            new_name='directory',
        ),
    ]
