# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20170512_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('posts', models.ManyToManyField(to='core.Post')),
            ],
        ),
    ]
