# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_postresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='config',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='controller',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='footer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='header',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['priority']},
        ),
        migrations.AlterModelOptions(
            name='paginator',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_datetime']},
        ),
        migrations.AlterModelOptions(
            name='sidebar',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='widget',
            options={'ordering': ['priority']},
        ),
        migrations.AddField(
            model_name='style',
            name='controller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Controller'),
        ),
        migrations.AddField(
            model_name='style',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Template'),
        ),
        migrations.AddField(
            model_name='config',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Style'),
        ),
    ]
