# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-11 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_page_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
                ('priority', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Controller')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Template')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ManyToManyField(blank=True, to='core.Image'),
        ),
    ]
